2024-12-03 13:14:58,787 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\fastapi\router.py", line 249, in handle_http_post
    return await self.run(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 200, in run
    result = await self.execute_operation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 111, in execute_operation
    request_data = await self.parse_http_body(request_adapter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 335, in parse_http_body
    data = self.parse_json(await request.get_body())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\asgi\__init__.py", line 70, in get_body
    return await self.request.body()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\requests.py", line 237, in body
    async for chunk in self.stream():
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\requests.py", line 231, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
2024-12-03 13:15:00,474 - uvicorn.error - ERROR - Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 401, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\cors.py", line 144, in simple_response
    await self.app(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 62, in wrapped_app
    raise exc
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\_exception_handler.py", line 51, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\fastapi\router.py", line 249, in handle_http_post
    return await self.run(
           ^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 200, in run
    result = await self.execute_operation(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 111, in execute_operation
    request_data = await self.parse_http_body(request_adapter)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\http\async_base_view.py", line 335, in parse_http_body
    data = self.parse_json(await request.get_body())
                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\strawberry\asgi\__init__.py", line 70, in get_body
    return await self.request.body()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\requests.py", line 237, in body
    async for chunk in self.stream():
  File "C:\Users\User\OneDrive\Desktop\Digital Land\Digital-Land-Server\venv\Lib\site-packages\starlette\requests.py", line 231, in stream
    raise ClientDisconnect()
starlette.requests.ClientDisconnect
